
locations:
  - fleeb@login.cluster.is.localnet
  - fleeb@wagner.is.localnet

silent: yes

# ['status', 'model', 'loc', 'address', 'started', 'duration', 'startup']
columns:
  status: yes
  model: yes
  address: yes
  # started: yes
  duration: yes
  startup: yes
  loc: yes
  port: yes




