
#silent: yes

#_base: [me]

_meta.script_name: status

_base: [remote]

user: fleeb


active-only: yes

silent: yes

no-active: yes


#_base: [jobs]
#_meta.script_name: submit

#q = fig status me --silent --only-active



