
#silent: yes

#_base: [me]

##########################

#_meta.script_name: vllm

#_base: [cluster]

#model: phi4
#bid: 1000

##########################

#_meta.script_name: serving
_meta.script_name: all-offline

_base: [all]

logpath: /home/fleeb/vllm.log

##########################

#_meta.script_name: launch
#
#_base: [cluster]
#_base: [llm]
#
#model: phi4
#bid: 1000

##########################

#_meta.script_name: status
#_base: [cluster]

#user: fleeb
#active-only: yes
#silent: yes
#no-active: yes

##########################


#_base: [jobs]
#_meta.script_name: submit

#q = fig status me --silent --only-active



