
parents: [repos]

command-path: /home/fleeb/todo.sh
update-cmds: true
include-cmds: true # in manifest

#include-date: true

#conda install -c eumetsat expect

template-path: /home/fleeb/workspace/code/mpi-cluster/data/template.sh

#working-dir: /home/fleeb/workspace/code/ideas
working-dir: /home/fleeb/workspace/code/NVAE

gpu: 1
ram: 48
cpu: 4

array: true

gpu-names: V100-32

time-limit: 10

bid: 50

avoid: p004


