
parents: [code]

cmd_path: /home/fleeb/workspace/mpi-cluster/run_n.sh

template: /home/fleeb/workspace/mpi-cluster/template.sh

dir: /home/fleeb/workspace/learn_rep

gpu: 1
mem: 48
cpu: 4

array: true

gpu_names: V100-32

bid: 50

avoid: p004


