
parents: [repos]

cmd_path: /home/fleeb/todo.sh
update_cmds: true
include_date: true

template: /is/ei/fleeb/workspace/mpi-cluster/data/template.sh

dir: /home/fleeb/workspace/learn_rep

gpu: 1
ram: 48
cpu: 4

array: true

gpu_names: V100-32

bid: 50

avoid: p004


