
parents: [repos]

command-path: /home/fleeb/todo.sh
update-cmds: true
include-cmds: true # in manifest

#include-date: true

#conda install -c eumetsat expect

template-path: /home/fleeb/workspace/code/mpi-cluster/data/template.sh

#working-dir: /home/fleeb/workspace/code/ideas
working-dir: /home/fleeb/workspace/code/NVAE

gpu: 1
ram: 48
cpu: 4

array: true

#gpu-names: [V100-32]
gpu-names: [A100-80, A100-40, V100-32, V100-32-PCI]
#gpu-names: [A100-80, A100-40, Quadro, V100-32, V100-32-PCI, V100-16, 2080]
#gpu-names: [K20, K80, P40, P100]

time-limit: 10

bid: 50

avoid: p004


