


git_repos:
  - /home/fleeb/workspace/code/belt
  - /home/fleeb/workspace/code/humpack
  - /home/fleeb/workspace/code/omni-fig
  - /home/fleeb/workspace/code/foundation
  - /home/fleeb/workspace/code/learn_rep
  - /home/fleeb/workspace/code/adversary

