


git_repos:
  - /home/fleeb/workspace/code/mpi-cluster
  - /home/fleeb/workspace/code/belt
#  - /home/fleeb/workspace/code/humpack
  - /home/fleeb/workspace/code/omni-fig
#  - /home/fleeb/workspace/code/foundation
#  - /home/fleeb/workspace/code/learn_rep
#  - /home/fleeb/workspace/code/NVAE
#  - /home/fleeb/workspace/code/plethora
#  - /home/fleeb/workspace/code/adversary
#  - /home/fleeb/workspace/code/ideas
#  - /home/fleeb/workspace/code/cladder
  - /home/fleeb/workspace/code/data-foundation
  - /home/fleeb/workspace/code/llm-evaluation

